from config import DEFAULT_CONFIG_IMAGES_SAVER
from config import DEFAULT_CONFIG_SCREENSHOOTER
from observer import ScreenGrabObserver
from imagesaver import ImageSaver
from screenshooter import Screenshooter
